@baseUrl=http://localhost:3000
@Content-Type=application/json

POST {{baseUrl}}/auth/register
Content-Type: {{Content-Type}}

{
  "name": "tom",
  "email": "tom2222@gmail.com",
    "password": "testpass2212#^$%word"
    }