@baseUrl=http://localhost:3000
@Content-Type=application/json

POST {{baseUrl}}/auth/register
Content-Type: {{Content-Type}}

{
  "name": "spike",
  "email": "spike2222@gmail.com",
  "password": "testpass2212#^$%word"
}